### ISSUE TITLE
Changelog for service-worker-mock v2?

### ISSUE THREAD

**Issue by kontrollanten** [zackargyle/service-workers#112]
In the latest release, 2.0, a lot of my tests are failing. I can't really figure out why, and I couldn't find any changelog or migration docs.

Test file https://github.com/hitta-skyddsrum/webclient-preact/blob/master/src/sw.test.js
Failing tests https://travis-ci.org/hitta-skyddsrum/webclient-preact/jobs/498155921

**Comment by makstheimba** [comment]
Same problem. I've installed latest version and it does not work, and I couldn't figure out why. However after discovering this issue I've tried 1.12.0 and it works as expected

**Comment by makstheimba** [comment]
Difference that I've noticed is that addEventListener is not mocked in v2.0. This might be a cause of a problem

**Comment by zackargyle** [comment]
@kontrollanten and @makstheimba. First off, my apologies! I'm on paternity leave right now and haven't had much time to work on updating documentation in particular. Here is the PR (#109) that had all of the breaking changes, hence the major version bump. I sadly will not have much time to help diagnose what is breaking in your tests this week, but maybe @kommander would be willing to help. Otherwise, I'd suggest sticking to the 1.x.x versions without the breaking changes.

**Comment by kommander** [comment]
Sorry for the missing Changelog, I am looking into the issues. Will put together a Changelog and migration guide asap when I am back from holidays after the 11th.

**Comment by chromakode** [comment]
Bumped into this today. I believe one cause is that `ServiceWorkerGlobalScope` now extends `EventTarget`.

`Object.assign(global, makeServiceWorkerEnv())` is no longer putting `EventTarget` methods like `addEventListener` into the global scope because they are no longer "own" properties of  `ServiceWorkerGlobalScope`.

**Comment by robatwilliams** [comment]
Symptom I'm seeing with v2 is that simply importing it will hang Jest before any tests are run.

**Comment by SterlingVix** [comment]
For anyone still experiencing this issue, I've just got `service-worker-mocks` running in our code.

1. It first required that we upgrade our app out of the beta version of Babel we were using (we were on `babel@^7.0.0-beta.44`). We upgraded to the current (as of Aug 2019) `babel@7.5.5`. Truthfully I don't remember the failure that led me to upgrade Babel (it was 2 weeks and A LOT of code ago); probably because we were using the old `@babel/preset-stage-3` env setting and it was throwing an error somewhere.

2. I rolled `service-worker-mock` back to the prod deploy at `service-worker-mock@1.10.1`.

It works as expected now; this test suite (testing the env) passes for me:

```

import _ from 'lodash';
import jestConfig from '../jest.config';
import makeServiceWorkerEnv from 'service-worker-mock';
import { cleanup } from '@testing-library/react'; // https://github.com/kentcdodds/react-testing-library

describe(`boot-service-worker`, () => {
  beforeEach(() => {
    cleanup();

    const defaultEnvOptions = { // See /service-worker-mock/index.
      locationUrl: `${jestConfig.testURL}/boot-service-worker.js`,
    };

    Object.assign(
      global,
      makeServiceWorkerEnv(defaultEnvOptions),
    );
  });

  afterEach(() => {
    jest.resetModules();
  });

  describe(`environment`, () => {
    it(`"self" and "self.listeners" should be defined.`, () => {
      expect(self).toBeDefined();
      expect(self.listeners).toBeDefined();
    });

    describe(`registers and listens for arbitrary events:`, () => { // turns out these aren't specifically defined, they are just defined dynamically.
      const events = [
        `activate`,
        `fetch`,
        `install`,
      ];

      events.forEach((event) => {
        test(`${event}.`, () => {
          self.addEventListener(event, _.noop);
          expect(self.listeners[event]).toBeDefined();
        });
      });
    }); // end describe(arbitrary events)


    describe(`has ServiceWorker Environment property:`, () => {
      const swProperties = [
        `caches`,
      ];

      swProperties.forEach((swProp) => {
        test(`${swProp}.`, async () => {
          expect(global[swProp]).toBeDefined();
        });
      });
    }); // end describe(ServiceWorker Env properties)


    describe(`Events have properties:`, () => {
      const eventProperties = [
        `waitUntil`,
      ];

      eventProperties.forEach((eventProp) => {
        test(`${eventProp}.`, async () => {
          self.addEventListener(`install`, (event) => {
            expect(event[eventProp]).toBeDefined();
          });

          await self.trigger('install');
        });
      });
    }); // end describe(event properties)
  }); // end describe(environment)
});
```

**Comment by deasems** [comment]
I think @chromakode identified the correct root cause. I can get v2 working if I make the `addEventListener` property enumerable:
```js
    const serviceWorkerEnv = makeServiceWorkerEnv();
    Object.defineProperty(serviceWorkerEnv, 'addEventListener', {
      value: serviceWorkerEnv.addEventListener,
      enumerable: true
    });
    Object.assign(global, serviceWorkerEnv)
```

**Comment by kevhender** [comment]
I have found that the way around this is to change the (e.g.) `self.listeners['fetch']` statements to use `self.listeners.get('fetch')`. `self.listeners` is a `Map` object in v2, not a simple object.

I have made PR #134 to reflect what changes should be made to test files.

**Comment by lukeapage** [comment]
Our problem (with jest hanging) was because we mocked out date and w3c-hr-time hangs if the date doesn't change.

They've fixed it:    https://github.com/jsdom/w3c-hr-time/blob/bfa8eb258553f28b64eb9ec24371ec4bb65f3253/lib/calculate-clock-offset.js#L17

but this package hasn't upgraded...

**Comment by lukeapage** [comment]
Another change we had to implement for v2 is that `await trigger(` doesn't wait for all promises, so we had to add
```
await ExtendableEvent.eventsDoneWaiting();
```
before assertions.
